# Generated by Django 5.2.1 on 2026-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="expancess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("amount", models.BigIntegerField()),
                ("note", models.CharField(max_length=10000)),
                ("expense_date", models.DateField(auto_now=True)),
                ("payment_method", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="user_login",
            fields=[
                (
                    "emial",
                    models.EmailField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
