# Generated by Django 5.2.1 on 2026-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_login",
            name="id",
        ),
        migrations.AlterField(
            model_name="user_login",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
