# Generated by Django 5.2.1 on 2026-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pro_app", "0002_remove_user_login_id_alter_user_login_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expancess",
            name="expense_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
